### ISSUE TITLE
change destinations to a list

### ISSUE THREAD

**Issue by sdetweil** [Jacopo1891/MMM-GoogleTrafficTimes#2]
instead of dest1,2,3

make a list []

of objects
{ label: "xyz", address:"whatever"},

....

**Comment by Jacopo1891** [comment]
I had this change planned since the first versions. Updated now, thanks for the tip!

**Comment by sdetweil** [comment]
just eliminates all the user input problems  and confusion on understanding. 
and removes the parsing on ':'.

and enables more that 3..

**Comment by Jacopo1891** [comment]
I agree with you completely.
