### ISSUE TITLE
Only load on a schedule?

### ISSUE THREAD

**Issue by cbuys** [Jacopo1891/MMM-GoogleTrafficTimes#5]
Would it be possible to have the drive times only show in the mornings during the week? Also have it not pulling data from Google during it's "downtime" if possible?

**Comment by Jacopo1891** [comment]
I'll take a look in the next few days! I will add these features.

**Comment by cbuys** [comment]
Is there a way to arrange several destinations in columns?

**Comment by Jacopo1891** [comment]
Unfortunately not yet 😄 
Would you like destinations to be arranged horizontally across multiple columns instead of vertically across multiple rows?

**Comment by cbuys** [comment]
For my current layout, horizontal would be fantastic. Have the option to switch back and forth might be nice though.

**Comment by Jacopo1891** [comment]
Check now! I hope this is what you were looking for 😄

**Comment by cbuys** [comment]
So sorry it took so long to get back to this. Everything you did worked amazing. Thank you so much.
