### ISSUE TITLE
Module visible between certain times

### ISSUE THREAD

**Issue by Rvnbrg** [Jacopo1891/MMM-GoogleTrafficTimes#7]
Hello,

I am trying to show the moduke at times between 05:00 - 09:00, 13:00 - 15:00, 21:00 - 23:00.
In my config I have starttines "05, 13, 21" and at endtimes I have "09, 15, 23".
But now the module doesn't display at any time.

Do you know how I can solve this?

Thank you

**Comment by Jacopo1891** [comment]
Hi! You have to split intervals one by one like this:
```
schedules: [
	{
		days: [], // Display at all times
		startHH: "05",
		startMM: "00",
		endHH: "09",
		endMM: "00"
    },
	{
		days: [], 
		startHH: "13",
		startMM: "00",
		endHH:"15",
		endMM: "00"
    },
	{
		days: [], 
		startHH:"21",
		startMM: "00",
		endHH:"23",
		endMM: "10"
	}
]
```

**Comment by Rvnbrg** [comment]
Thank you very much, I will try that

**Comment by Rvnbrg** [comment]
I can't get the module showing now at all. My config is 

```
{
            module: 'MMM-GoogleTrafficTimes',
            position: 'top_left',
            config: {
                key: '**GOOGLE API**',
                origin: 'home adress',
                destinations: [
			        {
			        	name: "work 1",
			        	address: "work adress 1"
			        },
			        {
			        	name: "work 2",
			        	address: "work adress 2"
			        },
				    {
			        	name: "work 3",
			        	address: "work adress3"
			        },
				{
					name: "(name of school)",
					adress: "adress of school"
				},
		        ],
                updateInterval: 900000,
                avoidHighways: false,
                avoidTolls: false,
                mode: 'driving',
                language: "en-EN",
                offsetTime: 25,
		        lastUpdate: true,
		        timeLastUpdateWarning: 1,
                horizontalLayout: true,
				schedules: [
					{
						days: [],
						startHH: "05",
						startMM: "00",
						endHH: "11",
						endMM: "45"
					},
					{
						days: [], 
						startHH: "13",
						startMM: "00",
						endHH:"15",
						endMM: "00"
					},
					{
						days: [], 
						startHH:"21",
						startMM: "00",
						endHH:"23",
						endMM: "00"
					},
				],
                debug: false
			},

```

**Comment by Jacopo1891** [comment]
Try with last update.
It should be fixed now!
Thanks! :)

**Comment by Rvnbrg** [comment]
Unfortunately not working yet. But I also cannot get the module working if I delete the schedule.

**Comment by Jacopo1891** [comment]
Have you have execute the install command after download?
Once in ~/MagicMirror/modules/MMM-GoogleTrafficTimes run:

`npm install`

Have you checked the logs? They might provide some information.

**Comment by Rvnbrg** [comment]
May I ask, how to view the logs? I am pretty new at this


Op vr 19 jul 2024 15:31 schreef Jacopo Campani ***@***.***>:

**Comment by Jacopo1891** [comment]
Never mind! [Read here](https://github.com/Jacopo1891/MMM-GoogleTrafficTimes?tab=readme-ov-file#debug)

**Comment by Rvnbrg** [comment]
I get a NPM error missing script "start"

**Comment by Jacopo1891** [comment]
I don't understand... could you paste the logs here?
Are you running the start command
`npm start dev | grep MMM-GoogleTrafficTimes`
in the main project directory to execute MM in dev mode?
All the other modules work except this one, right?

**Comment by Rvnbrg** [comment]
Yes that is correct. I ran MM in dev mode. Where can I find the log file?

I will try to reinstall the module because I had it working the first day I
installed it.

Op za 20 jul 2024 00:33 schreef Jacopo Campani ***@***.***>:

**Comment by Rvnbrg** [comment]
Can it be that the Google API causes this issue?

**Comment by Rvnbrg** [comment]
I woke up today and it is suddenly working! Thank you!

**Comment by Jacopo1891** [comment]
Oh... Cool! 💯
