### ISSUE TITLE
Working of schedule

### ISSUE THREAD

**Issue by Rvnbrg** [Jacopo1891/MMM-GoogleTrafficTimes#8]
Hello, I have a new question. How are the sschedules suppoosed to work?
In my case the module does not show/hide automatically, but after a restart it shows/hide according to the schedule at that current time.

**Comment by Jacopo1891** [comment]
The expected behavior is the module will disappear/appear according to the schedule every time it updates: by default, this happens approximately every 15 minutes, so it's normal that it doesn't show/hide exactly at the scheduled time.

**Comment by Rvnbrg** [comment]
Hello,
Thank you. That is how I expected it to work. However, for ex. Today it
should show since 13:00h. It is now 13:45 and it is still not showing. But
if I restart the mirror it will be visible.


Op do 25 jul 2024 13:41 schreef Jacopo Campani ***@***.***>:

**Comment by Jacopo1891** [comment]
You're right!
Try with last version.

**Comment by Rvnbrg** [comment]
Amazing!
Thank you for looking at it. It should show at 21:00 tonight. I will let you know if I got it working.

Thanks again!

**Comment by Rvnbrg** [comment]
Thanks again for your help! 
Module is now working as expected!

**Comment by Jacopo1891** [comment]
You're welcome! 
Thanks for your reports and coffee!🔥❤️
